# Generated by Django 6.0.4 on 2026-04-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_job_jobmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
